version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: turbo_postgres
    environment:
      POSTGRES_USER: anirudha
      POSTGRES_PASSWORD: Robin@930
      POSTGRES_DB: Velora
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
